// <auto-generated />
using System;
using HomeOffice.Calendar.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeOffice.Calendar.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240213200602_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("HomeOffice.Calendar.Models.HomeOfficeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DayInHomeOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayInOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Holiday")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeOfficePercent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublicHoliday")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SickDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Workday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HomeOfficeInfos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
